//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPFINALWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int AseguradoNº { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Domicilio { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string Nº_HistorialClinico { get; set; }
        public Nullable<bool> Sexo { get; set; }
    }
}
