//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPFINAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int NumIngreso { get; set; }
        public string NumeroHistorial { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string CodIdentificacion { get; set; }
        public int NumSala { get; set; }
        public int NumCama { get; set; }
        public string EnfermedadBase { get; set; }
    }
}
