//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPFINAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicos
    {
        public int Cod_Identificacion { get; set; }
        public string Nombre_Medico { get; set; }
        public string Apellido_Medico { get; set; }
        public string Especialidad { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public string Cargo { get; set; }
    }
}
